version: 0.2

env:
  exported-variables:
    - CODEBUILD_BUILD_ID

phases:
  build:
    commands:
      - AMD_TAR_FILE_PATH="${CODEBUILD_SRC_DIR_SignedArtifact}/ecs-agent-v${AGENT_VERSION}.tar"
      - ARM_TAR_FILE_PATH="${CODEBUILD_SRC_DIR_SignedArtifact}/ecs-agent-arm64-v${AGENT_VERSION}.tar"
      - AMD_TAR_FILE="ecs-agent-v${AGENT_VERSION}.tar"
      - ARM_TAR_FILE="ecs-agent-arm64-v${AGENT_VERSION}.tar"
      
      # Checksum commands output checksum followed by filename
      # Taking the checksum out explicitly using string length
      - AMD_MD5_CMD=$(md5sum $AMD_TAR_FILE_PATH)
      - AMD_MD5_CHECKSUM=${AMD_MD5_CMD::32}
      - AMD_SHA256_CMD=$(sha256sum $AMD_TAR_FILE_PATH)
      - AMD_SHA256_CHECKSUM=${AMD_SHA256_CMD::64}

      - ARM_MD5_CMD=$(md5sum $ARM_TAR_FILE_PATH)
      - ARM_MD5_CHECKSUM=${ARM_MD5_CMD::32}
      - ARM_SHA256_CMD=$(sha256sum $ARM_TAR_FILE_PATH)
      - ARM_SHA256_CHECKSUM=${ARM_SHA256_CMD::64}

      - RELEASE_DATE=$(date +'%Y%m%d')

      # Prepare agent.json config file
      # TODO initStagingConfig.release version configurable
      - |
        cat << EOF > agent.json
        {
          "agentReleaseVersion" : "$AGENT_VERSION",
          "releaseDate" : "$RELEASE_DATE",
          "initStagingConfig": {
            "release": "1"
          },
          "agentStagingConfig": {
            "releaseGitSha": "$GIT_COMMIT_SHA",
            "releaseGitShortSha": "$GIT_COMMIT_SHORT_SHA",
            "gitFarmRepoName": "MadisonContainerAgentExternal",
            "gitHubRepoName": "aws/amazon-ecs-agent",
            "gitFarmStageBranch": "v${AGENT_VERSION}-stage",
            "githubReleaseUrl": ""
          },
          "amazonLinux": {
            "artifactFilename": "${AMD_TAR_FILE}",
            "md5": "${AMD_MD5_CHECKSUM}",
            "signature": "${AMD_SHA256_CHECKSUM}"
          },
          "amazonLinux2Arm": {
            "artifactFilename": "${ARM_TAR_FILE}",
            "md5": "${ARM_MD5_CHECKSUM}",
            "signature": "${ARM_SHA256_CHECKSUM}"
          }
        }
        EOF
      
      # # Downloading agentVersionV2.json file from the All Dogs S3 Bucket
      # - aws s3 cp "$RESULTS_BUCKET_URI/agentVersionV2.json" ./agentVersionV2.json
      # # Grabbing the new current agent version
      # - CURR_VER=$(jq -r '.[] | select(.githubTrackingBranch=='\"$GITHUB_BRANCH_NAME\"') .releaseAgentVersion' agentVersionV2.json)
      # # Upating the versions 
      # - cat <<< $(jq '.[] | select (.githubTrackingBranch == '\"$GITHUB_BRANCH_NAME\"') .releaseAgentVersion = '\"$AGENT_VERSION\"' | select (.githubTrackingBranch == '\"$GITHUB_BRANCH_NAME\"') .currentAgentVersion = '\"$CURR_VER\"'' agentVersionV2.json | jq -s '.') > agentVersionV2.json
      # # Outputing updated agentVersionV2.json file
      # - cat agentVersionV2.json

      # # Downloading agentVersion-<branch>.json
      # - aws s3 cp "$RESULTS_BUCKET_URI/agentVersionV2.json" ./agentVersion-${GITHUB_BRANCH_NAME}.json
      # # Grabbing the new current agent version
      # - CURR_VER=$(jq -r '.releaseAgentVersion' agentVersion-${GITHUB_BRANCH_NAME}.json)
      # # Outputting updated agentVersion-<branch>.json file
      # - cat agentVersion-${}
      - ls
      - aws s3 cp s3://yemike-testbucket/agentVersionV2-${GITHUB_SOURCE_BRANCH_NAME}.json ./agentVersionV2-${GITHUB_SOURCE_BRANCH_NAME}.json
      - cat agentVersionV2-${GITHUB_SOURCE_BRANCH_NAME}.json

      # Grabbing the new current and release agent version
      - CURR_VER=$(jq -r '.releaseAgentVersion' agentVersionV2-${GITHUB_SOURCE_BRANCH_NAME}.json)
      # - RELEASE_VER=$(cat VERSION)
      - echo $CURR_VER
      - echo $AGENT_VERSION

      # Outputting updated agentVersion-<branch>.json file
      - cat <<< $(jq '.releaseAgentVersion = '\"$AGENT_VERSION\"' | .currentAgentVersion = '\"$CURR_VER\"'' agentVersionV2-${GITHUB_SOURCE_BRANCH_NAME}.json) > agentVersionV2-${GITHUB_SOURCE_BRANCH_NAME}-COPY.json
      # Formatting file
      - jq . agentVersionV2-${GITHUB_SOURCE_BRANCH_NAME}-COPY.json > agentVersionV2-${GITHUB_SOURCE_BRANCH_NAME}.json
      - cat agentVersionV2-${GITHUB_SOURCE_BRANCH_NAME}-COPY.json
      - cat agentVersionV2-${GITHUB_SOURCE_BRANCH_NAME}.json

artifacts:
  files:
    - agent.json
    - agentVersionV2-${GITHUB_SOURCE_BRANCH_NAME}.json
