version: 0.2

phases:
  build:
    commands:
      - echo Entered the build phase...
      - echo Build started on `date` 
      - ls
      - pwd
      - printenv
      - GITHUB_BRANCH=$(echo ${CODEBUILD_WEBHOOK_HEAD_REF} | cut -d "/" -f3-)
      - echo $GITHUB_BRANCH
      - echo $BRANCH
      - git branch
      - aws s3 cp s3://yemike-testbucket/agentVersionV2-${GITHUB_BRANCH}.json ./agentVersionV2-${GITHUB_BRANCH}.json
      - cat agentVersionV2-${GITHUB_BRANCH}.json

      # Grabbing the new current and release agent version
      - CURR_VER=$(jq -r '.releaseAgentVersion' agentVersionV2-${GITHUB_BRANCH}.json)
      - RELEASE_VER=$(cat VERSION)
      - echo $CURR_VER
      - echo $RELEASE_VER

      # # Outputting updated agentVersion-<branch>.json file
      # - cat <<< $(jq '.releaseAgentVersion = '\"$RELEASE_VER\"' | .currentAgentVersion = '\"$CURR_VER\"'' agentVersionV2-${GITHUB_BRANCH}.json) > agentVersionV2-${GITHUB_BRANCH}-COPY.json
      # # Formatting file
      # - jq . agentVersionV2-${GITHUB_BRANCH}-COPY.json > agentVersionV2-${GITHUB_BRANCH}.json
      # - cat agentVersionV2-${GITHUB_BRANCH}.json