version: 0.2

phases:
  build:
    commands:
      - echo Entered the build phase...
      - echo Build started on `date` 
      - ls
      - pwd
      - printenv
      - GITHUB_BRANCH=$(echo ${CODEBUILD_WEBHOOK_HEAD_REF} | cut -d "/" -f3-)
      - echo $GITHUB_BRANCH
      - git branch
      - BRANCH=$(echo ${CODEBUILD_WEBHOOK_BASE_REF} | cut -d "/" -f3-)
      - echo $BRANCH
      - GIT_COMMIT_SHA=$(git rev-parse $BRANCH)
      - GIT_COMMIT_SHORT_SHA=$(git rev-parse --short=8 $BRANCH)
      - aws s3 cp s3://yemike-testbucket/agentVersionV2-${GITHUB_BRANCH}.json ./agentVersionV2-${GITHUB_BRANCH}.json
      - cat agentVersionV2-${GITHUB_BRANCH}.json
      - RELEASE_DATE=$(date +'%Y%m%d')
      

      # Grabbing the new current and release agent version
      - CURR_VER=$(jq -r '.releaseAgentVersion' agentVersionV2-${GITHUB_BRANCH}.json)
      - RELEASE_VER=$(cat VERSION)
      - echo $CURR_VER
      - echo $RELEASE_VER

      # Outputting updated agentVersion-<branch>.json file
      - cat <<< $(jq '.releaseAgentVersion = '\"$RELEASE_VER\"' | .currentAgentVersion = '\"$CURR_VER\"'' agentVersionV2-${GITHUB_BRANCH}.json) > agentVersionV2-${GITHUB_BRANCH}-COPY.json
      # Formatting file by copying over temp file
      - jq . agentVersionV2-${GITHUB_BRANCH}-COPY.json > agentVersionV2-${GITHUB_BRANCH}.json
      - cat agentVersionV2-${GITHUB_BRANCH}-COPY.json
      - cat agentVersionV2-${GITHUB_BRANCH}.json

      - |
        cat << EOF > agent.json
        {
          "agentReleaseVersion" : "$RELEASE_VER",
          "releaseDate" : "$RELEASE_DATE",
          "initStagingConfig": {
            "release": "1"
          },
          "agentStagingConfig": {
            "releaseGitSha": "$GIT_COMMIT_SHA",
            "releaseGitShortSha": "$GIT_COMMIT_SHORT_SHA",
            "gitFarmRepoName": "MadisonContainerAgentExternal",
            "gitHubRepoName": "aws/amazon-ecs-agent",
            "gitFarmStageBranch": "v${RELEASE_VER}-stage",
            "githubReleaseUrl": ""
          }
        }
        EOF
      - cat agent.json
      - aws s3 cp ./agentVersionV2-${GITHUB_BRANCH}.json s3://yemike-testbucket/agentVersionV2-${GITHUB_BRANCH}.json
      - aws s3 cp ./agent.json s3://yemike-testbucket/$GIT_COMMIT_SHA/agent.json
