version: 0.2

phases:
  build:
    commands:
      - echo Entered the build phase...
      - echo Build started on `date` 
      - ls
      - printenv
      - GITHUB_BRANCH=$(echo ${CODEBUILD_WEBHOOK_HEAD_REF} | cut -d "/" -f3-)
      - echo $GITHUB_BRANCH
      - git branch