version: 0.2

phases:
  build:
    commands:
      - echo Entered the build phase...
      - echo Build started on `date` 
      - ls
      - pwd
      - printenv
      - GITHUB_BRANCH=$(echo ${CODEBUILD_WEBHOOK_HEAD_REF} | cut -d "/" -f3-)
      - echo $GITHUB_BRANCH
      - echo $BRANCH
      - git branch
      - aws s3 cp s3://yemike-testbucket/agentVersionV2-${GITHUB_BRANCH}.json ./agentVersionV2-${GITHUB_BRANCH}.json
      - cat agentVersionV2-${GITHUB_BRANCH}.json
      